### ISSUE TITLE
Can't install on OS X 10.10.3

### ISSUE THREAD

**Issue by evanmiltenburg** [alexklaeser/imgAnnotation#3]
I just tried to install this on OS X. From the screenshots it seems that you also got this working on a mac, but I can't figure it out. Here's what I've done so far:

* Install `qt` using `brew install qt`, followed by `brew linkapps qt`
* Set environment variables so as to create a makefile:
    * `PATH=$PATH:/usr/local/Cellar/qt/4.8.6/bin`
    * `QMAKESPEC=/usr/local/Cellar/qt/4.8.6/mkspecs/linux-g++`
    * `export QMAKESPEC PATH`
* Run qmake: `qmake imgAnnotation.pro` to get the makefile.
* Run `make` to build.

This returns the following:
    `ld: unknown option: -O1`
    `clang: error: linker command failed with exit code 1 (use -v to see invocation)`
    `make: *** [imgAnnotation] Error 1`

I feel like I'm close, but I have no idea what to do next. Can you help me?

**Comment by alexklaeser** [comment]
Hey Emiel,

thanks for your interest in this project. Yes, another fellow compiled the project for Mac OS X, I am not very familiar with Mac OS X, thus I cannot really help. You might try to remove the `-O1` from the final linking stage in the Makefile (as a workaround). Maybe it also helps to run `qmake-qt4 imgAnnotation.pro` (as described in the README file) instead of `qmake`?

I hope that helps!

**Comment by evanmiltenburg** [comment]
Hi Alex,

It works! Thank you very much. 

I removed the `-O1` flag, so that the LFLAGS line now looks like this: `LFLAGS = -Wl, -Wl,-rpath,/anaconda/lib`. (Anaconda is my package manager for Python.) Now I can run the imgAnnotation tool by double-clicking the binary file.

Small bug (or feature?): drawing bounding boxes works fine, but if you make a mistake and delete the object to draw a new bounding box, the number is not reset. So an image containing a single object might have an annotation for `object: 3` simply because the annotators didn't get it right the first two times.

**Comment by alexklaeser** [comment]
Cool :) ! Not sure, but usually QT should get this right. By curiosity, which QT version are you using? Did you try `qmake-qt4`?

Thanks for letting me know this little bug. Please feel free to open a new issue for the bug. And of course, you are welcome to propose a patch if you feel like.

**Comment by evanmiltenburg** [comment]
`Emiel$ qmake --version`
`QMake version 2.01a`
`Using Qt version 4.8.6 in /anaconda/lib`

I don't think there was a qmake-qt4 option when I installed qmake using Homebrew. (I switched to Homebrew at some point because MacPorts (which I think does offer qmake-qt4) seems to require *loads* of dependencies to install even the simplest utility.)

**Comment by alexklaeser** [comment]
Alright, thanks. No, than it should be fine... qmake-qt4 is only necessary for Qt5, AFAIS.
Thanks for the new issue!
